apiVersion: apps/v1
kind: Deployment
metadata:
  name: geofinder
  labels:
    app: geofinder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geofinder
  template:
    metadata:
      labels:
        app: geofinder
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: geofinder
          image: geofinder-image
          command:
            - '/app/geofinder'
          args:
            # - '-prom_endpoint'
            # - '/metrics'
            # - '-prom_listen_addr'
            # - ':2112'

          ports:
            # - name: metrics
            #   protocol: "TCP"
            #   containerPort: 2112
            - name: service
              protocol: "TCP"
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTPS
          resources:
            limits:
              cpu: "80m"
              memory: "40M"
