apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geofinder
commonLabels:
  app: geofinder

resources:
  - deployment.yml
  - service.yml

images:
- name: geofinder-image
  newName: geofinder
  newTag: latest
